version: '3.1'
services:
  apipainel-db:
    container_name: apipainel_db
    image: postgres
    environment:
      POSTGRES_DB: 'dbapipainel'
      POSTGRES_PASSWORD: 'Mec_2022'
      POSTGRES_USER: 'dbapipainel'
    ports:
      - '5432:5432'
    volumes:
      - ./db/dashboard-backend/pgdata:/var/lib/postgresql
    networks:
      - apipainel

  apipainel-api:
    container_name: apipainel_api
    build:
      context: ../dashboard-backend
      dockerfile: Dockerfile
    ports:
      - 7080:80
    environment:
      APP_ENV: 'local'
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost:7080'
      DATABASE_DRIVER: 'pdo_pgsql'
      DATABASE_HOST: apipainel_db
      DATABASE_PORT: '5432'
      DATABASE_NAME: 'dbapipainel'
      DATABASE_USER: 'dbapipainel'
      DATABASE_PASSWORD: 'Mec_2022'
      restart: always
    volumes:
      - ../dashboard-backend:/var/www/html/api
    depends_on:
      - apipainel-db
    networks:
      - apipainel

  react-google-charts:
    container_name: react-google_charts 
    build:
      context: ../react-google-charts/google-charts 
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_BASE_URL_BACKEND: ' http://localhost:7080/api'
    volumes:
      - ../react-google-charts/google-charts:/var/www/html
    ports:
      - 7081:3000
    command: >
       sh -c "npm install && npm start" 
  
    networks:
      - apipainel

networks:
  apipainel:
    driver: bridge
